AllCops:
  Exclude:
    - config/initializers/**
    - bin/**
    - vendor/**/*
    - spec/**/*
    - db/seeds/seed_data.rb
    - db/schema.rb
    - db/migrate/**
    - app/controllers/invitations_controller.rb
    - Gemfile
    - Rakefile
  TargetRubyVersion: 2.3

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  ConsistentQuotesInMultiline: false

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
