TYPE = "example"
require_relative "./helpers"
require_relative "./seeds/admins"

require_relative "./seeds/destinations"
require_relative "./seeds/regions"
require_relative "./seeds/ships"
require_relative "./seeds/voyages"
require_relative "./seeds/cabins"
require_relative "./seeds/activities"
